In [1]:
import scipy.io
import pandas as pd
import numpy as np
import random
import csv
import matplotlib.pyplot as plt

In [2]:
data_calib_a = scipy.io.loadmat('BCICIV_1_mat\BCICIV_calib_ds1a.mat')
data_eval_a = scipy.io.loadmat('BCICIV_1_mat\BCICIV_eval_ds1a.mat')

In [3]:
data_calib_a

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Mon Jul  7 18:53:37 2008',
 '__version__': '1.0',
 '__globals__': [],
 'mrk': array([[(array([[  2091,   2891,   3691,   4491,   5291,   6091,   6891,   7692,
                   8492,   9292,  10092,  10892,  11692,  12492,  13292,  16294,
                  17094,  17894,  18694,  19494,  20294,  21094,  21894,  22694,
                  23494,  24294,  25094,  25894,  26694,  27494,  30495,  31295,
                  32095,  32895,  33695,  34495,  35295,  36095,  36895,  37695,
                  38495,  39295,  40095,  40895,  41695,  44696,  45496,  46296,
                  47096,  47896,  48696,  49496,  50296,  51096,  51896,  52696,
                  53496,  54296,  55096,  55896,  58895,  59695,  60495,  61295,
                  62095,  62895,  63695,  64495,  65295,  66095,  66895,  67695,
                  68495,  69295,  70095,  73094,  73894,  74694,  75495,  76295,
                  77095,  77895,  78695,  7

In [4]:
data_calib_a.keys()

dict_keys(['__header__', '__version__', '__globals__', 'mrk', 'cnt', 'nfo'])

In [5]:
data_calib_a["__header__"]

b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Mon Jul  7 18:53:37 2008'

In [6]:
data_calib_a["__version__"]

'1.0'

In [7]:
data_calib_a["__globals__"]

[]

## mrk: structure of target cue information with fields (the file of evaluation data does not contain this variable)
 - pos: vector of positions of the cue in the EEG signals given in unit sample, length #cues
 - y: vector of target classes (-1 for class one or 1 for class two), length #cues

In [8]:
data_calib_a["mrk"]

array([[(array([[  2091,   2891,   3691,   4491,   5291,   6091,   6891,   7692,
                  8492,   9292,  10092,  10892,  11692,  12492,  13292,  16294,
                 17094,  17894,  18694,  19494,  20294,  21094,  21894,  22694,
                 23494,  24294,  25094,  25894,  26694,  27494,  30495,  31295,
                 32095,  32895,  33695,  34495,  35295,  36095,  36895,  37695,
                 38495,  39295,  40095,  40895,  41695,  44696,  45496,  46296,
                 47096,  47896,  48696,  49496,  50296,  51096,  51896,  52696,
                 53496,  54296,  55096,  55896,  58895,  59695,  60495,  61295,
                 62095,  62895,  63695,  64495,  65295,  66095,  66895,  67695,
                 68495,  69295,  70095,  73094,  73894,  74694,  75495,  76295,
                 77095,  77895,  78695,  79495,  80295,  81095,  81895,  82695,
                 83495,  84295,  87294,  88094,  88894,  89694,  90494,  91294,
                 92094,  92894,  93694,

## pos: vector of positions of the cue in the EEG signals given in unit sample, length #cues

In [75]:
pos = data_calib_a["mrk"]["pos"][0][0][0]
pos

array([  2091,   2891,   3691,   4491,   5291,   6091,   6891,   7692,
         8492,   9292,  10092,  10892,  11692,  12492,  13292,  16294,
        17094,  17894,  18694,  19494,  20294,  21094,  21894,  22694,
        23494,  24294,  25094,  25894,  26694,  27494,  30495,  31295,
        32095,  32895,  33695,  34495,  35295,  36095,  36895,  37695,
        38495,  39295,  40095,  40895,  41695,  44696,  45496,  46296,
        47096,  47896,  48696,  49496,  50296,  51096,  51896,  52696,
        53496,  54296,  55096,  55896,  58895,  59695,  60495,  61295,
        62095,  62895,  63695,  64495,  65295,  66095,  66895,  67695,
        68495,  69295,  70095,  73094,  73894,  74694,  75495,  76295,
        77095,  77895,  78695,  79495,  80295,  81095,  81895,  82695,
        83495,  84295,  87294,  88094,  88894,  89694,  90494,  91294,
        92094,  92894,  93694,  94494,  97385,  98185,  98985,  99785,
       100585, 101385, 102185, 102985, 103785, 104585, 105385, 106185,
      

In [81]:
pos.shape

(200,)

## y: vector of target classes (-1 for class one or 1 for class two), length #cues

In [80]:
target_class = data_calib_a["mrk"]["y"][0][0][0]
target_class

array([ 1,  1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1, -1, -1, -1,  1, -1,
       -1,  1, -1,  1,  1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1,  1,  1,  1, -1, -1,  1, -1,  1, -1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1,  1, -1,  1, -1,
        1, -1, -1, -1,  1, -1, -1, -1,  1, -1,  1, -1, -1, -1,  1,  1,  1,
       -1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1,  1, -1,  1,
        1,  1, -1,  1,  1, -1,  1, -1,  1, -1, -1, -1, -1,  1,  1, -1,  1,
        1,  1,  1, -1,  1, -1, -1,  1,  1, -1, -1,  1,  1,  1,  1,  1,  1,
        1, -1, -1, -1, -1,  1, -1, -1,  1, -1, -1, -1,  1,  1, -1, -1,  1,
        1, -1,  1,  1,  1,  1, -1,  1, -1,  1, -1,  1, -1, -1, -1, -1, -1,
        1,  1,  1,  1, -1, -1, -1, -1, -1,  1,  1, -1,  1, -1, -1, -1,  1,
       -1,  1, -1,  1, -1, -1,  1, -1, -1, -1,  1,  1,  1], dtype=int16)

In [82]:
target_class.shape

(200,)

## cnt: the continuous EEG signals, size [time x channels]. To convert it to uV values, use cnt= 0.1*double(cnt)

In [85]:
cnt = data_calib_a["cnt"]
cnt

array([[  -3,   -3,   -3, ...,    2,    7,    5],
       [ -25,  -21,  -26, ...,   19,   60,   45],
       [ -34,  -15,  -52, ...,   37,  130,   98],
       ...,
       [2524, 2672, 2347, ..., 1167, 1620, 1205],
       [2561, 2706, 2385, ..., 1249, 1693, 1210],
       [2606, 2759, 2457, ..., 1366, 1838, 1263]], dtype=int16)

In [86]:
cnt.shape

(190594, 59)

## nfo: structure providing additional information with fields
- fs: sampling rate,
- clab: cell array of channel labels,
- classes: cell array of the names of the motor imagery classes,
- xpos: x-position of electrodes in a 2d-projection,
- ypos: y-position of electrodes in a 2d-projection.

In [87]:
data_calib_a["nfo"]

array([[(array([[100]], dtype=uint8), array([[array(['left'], dtype='<U4'), array(['foot'], dtype='<U4')]],
              dtype=object), array([[array(['AF3'], dtype='<U3'), array(['AF4'], dtype='<U3'),
                array(['F5'], dtype='<U2'), array(['F3'], dtype='<U2'),
                array(['F1'], dtype='<U2'), array(['Fz'], dtype='<U2'),
                array(['F2'], dtype='<U2'), array(['F4'], dtype='<U2'),
                array(['F6'], dtype='<U2'), array(['FC5'], dtype='<U3'),
                array(['FC3'], dtype='<U3'), array(['FC1'], dtype='<U3'),
                array(['FCz'], dtype='<U3'), array(['FC2'], dtype='<U3'),
                array(['FC4'], dtype='<U3'), array(['FC6'], dtype='<U3'),
                array(['CFC7'], dtype='<U4'), array(['CFC5'], dtype='<U4'),
                array(['CFC3'], dtype='<U4'), array(['CFC1'], dtype='<U4'),
                array(['CFC2'], dtype='<U4'), array(['CFC4'], dtype='<U4'),
                array(['CFC6'], dtype='<U4'), array(['CFC8

## fs: sampling rate - 100 in this case

In [24]:
data_calib_a["nfo"]["fs"]

array([[array([[100]], dtype=uint8)]], dtype=object)

## classes: cell array of the names of the motor imagery classes,

In [16]:
data_calib_a["nfo"]["classes"]

array([[array([[array(['left'], dtype='<U4'), array(['foot'], dtype='<U4')]],
              dtype=object)                                                  ]],
      dtype=object)

## clab: cell array of channel labels

In [45]:
clab = data_calib_a["nfo"]["clab"][0][0][0]
clab

array([array(['AF3'], dtype='<U3'), array(['AF4'], dtype='<U3'),
       array(['F5'], dtype='<U2'), array(['F3'], dtype='<U2'),
       array(['F1'], dtype='<U2'), array(['Fz'], dtype='<U2'),
       array(['F2'], dtype='<U2'), array(['F4'], dtype='<U2'),
       array(['F6'], dtype='<U2'), array(['FC5'], dtype='<U3'),
       array(['FC3'], dtype='<U3'), array(['FC1'], dtype='<U3'),
       array(['FCz'], dtype='<U3'), array(['FC2'], dtype='<U3'),
       array(['FC4'], dtype='<U3'), array(['FC6'], dtype='<U3'),
       array(['CFC7'], dtype='<U4'), array(['CFC5'], dtype='<U4'),
       array(['CFC3'], dtype='<U4'), array(['CFC1'], dtype='<U4'),
       array(['CFC2'], dtype='<U4'), array(['CFC4'], dtype='<U4'),
       array(['CFC6'], dtype='<U4'), array(['CFC8'], dtype='<U4'),
       array(['T7'], dtype='<U2'), array(['C5'], dtype='<U2'),
       array(['C3'], dtype='<U2'), array(['C1'], dtype='<U2'),
       array(['Cz'], dtype='<U2'), array(['C2'], dtype='<U2'),
       array(['C4'], dtype='<U

In [48]:
clab.shape

(59,)

Flatten clab and remove the type

In [63]:
clab_flatten = np.concatenate(clab).ravel()
clab_flatten

array(['AF3', 'AF4', 'F5', 'F3', 'F1', 'Fz', 'F2', 'F4', 'F6', 'FC5',
       'FC3', 'FC1', 'FCz', 'FC2', 'FC4', 'FC6', 'CFC7', 'CFC5', 'CFC3',
       'CFC1', 'CFC2', 'CFC4', 'CFC6', 'CFC8', 'T7', 'C5', 'C3', 'C1',
       'Cz', 'C2', 'C4', 'C6', 'T8', 'CCP7', 'CCP5', 'CCP3', 'CCP1',
       'CCP2', 'CCP4', 'CCP6', 'CCP8', 'CP5', 'CP3', 'CP1', 'CPz', 'CP2',
       'CP4', 'CP6', 'P5', 'P3', 'P1', 'Pz', 'P2', 'P4', 'P6', 'PO1',
       'PO2', 'O1', 'O2'], dtype='<U4')

## xpos and ypos of electrodes in a 2d-projection

In [34]:
position = np.concatenate((data_calib_a["nfo"]["xpos"][0][0], data_calib_a["nfo"]["ypos"][0][0]), axis = 1)
position

array([[-0.20109028,  0.68656518],
       [ 0.20109028,  0.68656518],
       [-0.48547489,  0.52547424],
       [-0.32894737,  0.46520183],
       [-0.16535231,  0.43208641],
       [ 0.        ,  0.421549  ],
       [ 0.16535231,  0.43208641],
       [ 0.32894737,  0.46520183],
       [ 0.48547489,  0.52547424],
       [-0.60591541,  0.27165704],
       [-0.39919579,  0.23384348],
       [-0.19765935,  0.21394494],
       [ 0.        ,  0.20773757],
       [ 0.19765935,  0.21394494],
       [ 0.39919579,  0.23384348],
       [ 0.60591541,  0.27165704],
       [-0.74834683,  0.15177169],
       [-0.52472976,  0.12553103],
       [-0.30963911,  0.11086096],
       [-0.10226303,  0.10426648],
       [ 0.10226303,  0.10426648],
       [ 0.30963911,  0.11086096],
       [ 0.52472976,  0.12553103],
       [ 0.74834683,  0.15177169],
       [-0.87719298,  0.        ],
       [-0.64569058,  0.        ],
       [-0.421549  ,  0.        ],
       [-0.20773757,  0.        ],
       [ 0.        ,

## Postion and label

In [66]:
postion_clap = np.concatenate((position, clab_flatten.reshape(-1,1)), axis = 1)
postion_clap

array([['-0.20109028464758363', '0.6865651771052461', 'AF3'],
       ['0.20109028464758363', '0.6865651771052461', 'AF4'],
       ['-0.48547489245766257', '0.5254742370339627', 'F5'],
       ['-0.32894736842105265', '0.4652018297279918', 'F3'],
       ['-0.16535230938896844', '0.43208640720881303', 'F1'],
       ['0.0', '0.4215490013382115', 'Fz'],
       ['0.16535230938896844', '0.43208640720881303', 'F2'],
       ['0.32894736842105265', '0.4652018297279918', 'F4'],
       ['0.48547489245766257', '0.5254742370339627', 'F6'],
       ['-0.605915412132058', '0.2716570424217247', 'FC5'],
       ['-0.39919578789655963', '0.23384347850759124', 'FC3'],
       ['-0.1976593484504406', '0.21394493707763337', 'FC1'],
       ['0.0', '0.20773756505037197', 'FCz'],
       ['0.1976593484504406', '0.21394493707763337', 'FC2'],
       ['0.39919578789655963', '0.23384347850759124', 'FC4'],
       ['0.605915412132058', '0.2716570424217247', 'FC6'],
       ['-0.7483468341419532', '0.15177169088329834', '

## Merging cnt with sensor label